### ISSUE TITLE
Change pinning once we have a working Windows version for this package

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/freetype-feedstock#4]
Review pinning for
- [X] matplotlib (https://github.com/conda-forge/matplotlib-feedstock/pull/21)
- [X] pillow (https://github.com/conda-forge/pillow-feedstock/pull/6)
- [X] fontconfig (https://github.com/conda-forge/fontconfig-feedstock/pull/3)
- [x] cairo (https://github.com/conda-forge/cairo-feedstock/pull/3)

**Comment by jakirkham** [comment]
Looks like the `cairo` PR was merged. So, have check that off the list. Are there other actionables or can this be closed?

**Comment by ocefpaf** [comment]
I merged the final cairo PR today as we were using the default version in some packages due to the low build number.
