### ISSUE TITLE
Incorrect pinnning

### ISSUE THREAD

**Issue by pelson** [conda-forge/freetype-feedstock#5]
The recipe is pinning against libpng 1.6*, not the recommended pinning of https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies. This has resulted in issues such as https://github.com/matplotlib/matplotlib/issues/6511.

**Comment by ocefpaf** [comment]
We also did `fontconfig` and rebuilt `matplotlib` and `cairo`. However, the same issue still exist with `qt` now.
